// Conversation routes: list threads, read a thread, post a message.
// The character reply is generated by the AI layer; any structured
// intent is validated + applied by the engine before the state is saved.

import type { FastifyInstance } from 'fastify';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import type { ConversationReplyResult, Message } from '@onze/shared';
import { loadGame, saveGame } from '../db/store.js';
import { toClientState, type StoredGame } from '../db/model.js';
import { refreshStandings } from '../engine/tick.js';
import { generateReply, suggestionsFor, updateMemory } from '../ai/conversation.js';
import { applyIntent } from '../ai/intents.js';

function requireGame(id: string): StoredGame {
  const g = loadGame(id);
  if (!g) throw { statusCode: 404, message: 'Carrière introuvable.' };
  return g;
}

function threadFor(game: StoredGame, characterId: string): Message[] {
  const conv = game.conversations.find((c) => c.characterId === characterId);
  if (conv) return conv.messages;
  const created = { characterId, messages: [] as Message[] };
  game.conversations.push(created);
  return created.messages;
}

export async function conversationRoutes(app: FastifyInstance): Promise<void> {
  // thread list (one row per character, with last message + unread hint)
  app.get<{ Params: { id: string } }>('/api/game/:id/conversations', async (req) => {
    const game = requireGame(req.params.id);
    return game.characters.map((c) => {
      const conv = game.conversations.find((cv) => cv.characterId === c.id);
      const last = conv?.messages[conv.messages.length - 1] ?? null;
      return {
        character: c,
        lastMessage: last?.text ?? null,
        lastRole: last?.role ?? null,
        suggestions: suggestionsFor(game, c),
      };
    });
  });

  // full thread for a character
  app.get<{ Params: { id: string; cid: string } }>('/api/game/:id/conversation/:cid', async (req) => {
    const game = requireGame(req.params.id);
    const character = game.characters.find((c) => c.id === req.params.cid);
    if (!character) throw { statusCode: 404, message: 'Personnage introuvable.' };
    const messages = threadFor(game, character.id);
    return { character, messages, suggestions: suggestionsFor(game, character) };
  });

  // post a message → character reply (+ validated effect)
  app.post<{ Params: { id: string; cid: string }; Body: unknown }>(
    '/api/game/:id/conversation/:cid',
    async (req): Promise<ConversationReplyResult> => {
      const { text } = z.object({ text: z.string().min(1).max(500) }).parse(req.body);
      const game = requireGame(req.params.id);
      const character = game.characters.find((c) => c.id === req.params.cid);
      if (!character) throw { statusCode: 404, message: 'Personnage introuvable.' };

      const messages = threadFor(game, character.id);
      const now = Date.now();

      // 1. record the player's message
      const playerMsg: Message = { id: nanoid(6), role: 'player', text, week: game.week, ts: now };
      messages.push(playerMsg);

      // 2. generate the character reply (mock or real LLM)
      const { reply, intent } = await generateReply(game, character, messages, text);

      // 3. validate + apply any structured effect (engine owns the numbers)
      const effect = applyIntent(game, character, intent);

      // 4. record the character reply (+ a system line if an effect landed)
      const charMsg: Message = { id: nanoid(6), role: 'character', text: reply, week: game.week, ts: now + 1 };
      messages.push(charMsg);
      if (effect?.ok) {
        messages.push({ id: nanoid(6), role: 'system', text: effect.summary, week: game.week, ts: now + 2 });
      }

      // 5. compress memory + mark the character's notifications read
      updateMemory(character, text, reply);
      game.notifications.forEach((n) => {
        if (n.characterId === character.id) n.unread = false;
      });

      saveGame(game);
      refreshStandings(game);
      return {
        message: charMsg,
        effect,
        state: toClientState(game),
        suggestions: suggestionsFor(game, character),
      };
    },
  );
}
